version: 2

x-defaults: &defaults
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "07:00"
    timezone: "Europe/Berlin"

updates:
  - package-ecosystem: "github-actions"
    << : *defaults

  - package-ecosystem: "pip"
    << : *defaults

  - package-ecosystem: "docker"
    << : *defaults