version: 2

# One day, github will support yaml aliases
# x-defaults: &defaults
# directory: "/"
# schedule:
#   interval: "weekly"
#   day: "monday"
#   time: "07:00"
#   timezone: "Europe/Berlin"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"